### ISSUE TITLE
Migrate to a web application

### ISSUE THREAD

**Issue by experdot** [experdot/AutoPaint.NET#6]
### Overview
For the past year, I've been working mainly on TypeScript. For the reason, I plan to move the code to the web platform next, and then decide what to do later.

- Migrate to [general-engine](https://github.com/experdot/general-engine) gallery

### What about this repository?
Absolutely, I won't give up the .NET desktop application. I'm just trying to do something to move the project forward.

**Comment by experdot** [comment]
I can't stand the low performance of web platform: On the same computer, the HTML5 canvas can draw 500 circles per frame but 30,000 circles Win2D do.

**Comment by 418888967** [comment]
2020.4.1的代码下载了以后编译 出现了快捷键失效的情况？暂停 继续 停止等快捷键

**Comment by experdot** [comment]
> 2020.4.1的代码下载了以后编译 出现了快捷键失效的情况？暂停 继续 停止等快捷键

已修复

**Comment by 418888967** [comment]
@ experdot

   非常感谢您的修复，我下载下来，用VS2017编译生成了解决方案，但是依然还是无法使用快捷键，或者是我编译的方式出了错误？如果您方便的话，是否可以上传您亲自编译上传的最终执行程序？

**Comment by 418888967** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"experdot"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月5日(星期天) 中午1:07
收件人:&nbsp;"experdot/AutoPaint.NET"<AutoPaint.NET@noreply.github.com&gt;;
抄送:&nbsp;"达人小猪"<418888967@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [experdot/AutoPaint.NET] Migrate to a web application (#6)





  
2020.4.1的代码下载了以后编译 出现了快捷键失效的情况？暂停 继续 停止等快捷键
  
已修复
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.




@ experdot




&nbsp; &nbsp;非常感谢您抽出时间完成的修复，我下载下来，用VS2017编译生成了解决方案，但是依然还是无法使用快捷键，或者是我编译的方式出了错误？如果您方便的话，是否可以上传您亲自编译上传的最终执行程序？




是否可以烦请您帮助检查一下我的编译过程存在的问题，再次感谢您！

**Comment by experdot** [comment]
> @ experdot
> 
> 非常感谢您的修复，我下载下来，用VS2017编译生成了解决方案，但是依然还是无法使用快捷键，或者是我编译的方式出了错误？如果您方便的话，是否可以上传您亲自编译上传的最终执行程序？

快捷键有延迟，长按一会儿即可

**Comment by 418888967** [comment]
好的 您说的是长按 不是连续点击是吗?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "experdot"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 凌晨0:05
收件人: "experdot/AutoPaint.NET"<AutoPaint.NET@noreply.github.com&gt;; 
抄送: "达人小猪"<418888967@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [experdot/AutoPaint.NET] Migrate to a web application (#6)





  
@ experdot
 
非常感谢您的修复，我下载下来，用VS2017编译生成了解决方案，但是依然还是无法使用快捷键，或者是我编译的方式出了错误？如果您方便的话，是否可以上传您亲自编译上传的最终执行程序？
  
快捷键有延迟，长按一会儿即可

**Comment by 418888967** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"experdot"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 凌晨0:05
收件人:&nbsp;"experdot/AutoPaint.NET"<AutoPaint.NET@noreply.github.com&gt;;
抄送:&nbsp;"达人小猪"<418888967@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [experdot/AutoPaint.NET] Migrate to a web application (#6)





  
@ experdot
 
非常感谢您的修复，我下载下来，用VS2017编译生成了解决方案，但是依然还是无法使用快捷键，或者是我编译的方式出了错误？如果您方便的话，是否可以上传您亲自编译上传的最终执行程序？
  
快捷键有延迟，长按一会儿即可
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.







抱歉，我重试了几次 依然还是无效，我的编译应该有问题，可否请您发给我一份编译好的版本rar。 谢谢您！ 真的很喜欢您的作品。







我留意到代码中还有”打开一张下载好的图片”等功能 会在后续添加吗

**Comment by 418888967** [comment]
大神 我再次测试了您的程序&nbsp; 发现软件刚打开的时候&nbsp; &nbsp;第一次使用快捷键暂停 停止的时候可以有效，但是在不关闭软件的前提下&nbsp; 再次截取图片画图&nbsp; 或者正常使用 快捷键就依然处于失效状态， 必须将软件关闭重新打开才可以&nbsp; 烦请您在检查一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "experdot"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 凌晨0:05
收件人: "experdot/AutoPaint.NET"<AutoPaint.NET@noreply.github.com&gt;; 
抄送: "达人小猪"<418888967@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [experdot/AutoPaint.NET] Migrate to a web application (#6)





  
@ experdot
 
非常感谢您的修复，我下载下来，用VS2017编译生成了解决方案，但是依然还是无法使用快捷键，或者是我编译的方式出了错误？如果您方便的话，是否可以上传您亲自编译上传的最终执行程序？
  
快捷键有延迟，长按一会儿即可

**Comment by experdot** [comment]
Closed. I developed a new algorithm and it will be hosted on UWP mainly.

**Comment by 418888967** [comment]
------------------ 原始邮件 ------------------
***@***.***&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 凌晨0:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [experdot/AutoPaint.NET] Migrate to a web application (#6)





  
大神 Autopaint.net 更新了吗？是否可以请您给我发一份编译好的版本？ 谢谢您&nbsp;&nbsp;




&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;---您的小粉丝

**Comment by experdot** [comment]
@418888967 现在是UWP程序，只能在 Win10 上运行
